Pages/Dashboard.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SpotifyAPI.Web;
using SpotifyAPI.Web.Enums;
using SpotifyAPI.Web.Models;
using Tunix.Classes;
using Tunix.Extensions;
using Tunix.Models;

namespace Tunix
{
    public class DashboardModel : PageModel
    {
        public string AccessToken { get; set; }

        SpotifyWebAPI api = new SpotifyWebAPI();
        Queue<FullTrack> queue = new Queue<FullTrack>();

        public void OnGet()
        {
            AuthInfo authInfo = HttpContext.Session.GetObject<AuthInfo>("AuthInfo");
            AccessToken = authInfo.AccessToken;
        }

        public JsonResult OnGetSearch2(string SearchRequest)
        {

            api = HttpContext.Session.GetObject<SpotifyWebAPI>("api");
            SearchItem SearchResult = api.SearchItems(SearchRequest, SearchType.Track);

            return new JsonResult(SearchResult);
            
        }

        public ActionResult OnGetQueueAdd(string Id)
        {
            api = HttpContext.Session.GetObject<SpotifyWebAPI>("api");
            FullTrack track = api.GetTrack(Id);
            if (track.Error == null)
            {
                Queue<FullTrack> queueSession = HttpContext.Session.GetObject<Queue<FullTrack>>("queue");

                if (queueSession != null)
                {
                    queue = queueSession;
                }
                 
                queue.Enqueue(track);
                HttpContext.Session.SetObject("queue", queue);

                return new JsonResult(queue);
            }
            else
            {
                return new JsonResult(track.Error);
            }
        }
 
        public void OnGetPlayQueue(string Id)
        {
            string DeviceID = "";

            SpotifyWebAPI api = HttpContext.Session.GetObject<SpotifyWebAPI>("api");

            string trackuri = "spotify:track:"+Id;

            AvailabeDevices Device = api.GetDevices();

            foreach (var devices in Device.Devices)
            {
                if(devices.Name == "Tunix")
                {
                    DeviceID = devices.Id;
                    break;
                }
            }

            if (Device.Devices != null)
            {
                List<string> trackuris = new List<string> { trackuri };
                ErrorResponse error = api.ResumePlayback(DeviceID, null, trackuris, 0, 0);
                
            }
        }
    }
}

Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Tunix.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Tunix.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Tunix.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/SpotifyLogin.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using SpotifyAPI.Web;
using SpotifyAPI.Web.Models;
using SpotifyAPI.Web.Enums;
using Tunix.Extensions;
using Tunix.Models;

//Het is niet mogelijk om op een voor mij toegankelijke manier een POST request aan te maken naar Spotify.
//Vandaar dat er een authentication scheme wordt gebruikt. [Authorize] maakt de pagina onbruikbaar voor andere code behalve de auth
//Na het verifieren wordt ge-redirect van Spotify naar /callback

namespace Tunix.Pages
{
    [Authorize(AuthenticationSchemes = "Spotify")]
    public class SpotifyLoginModel : PageModel
    {
        //Niks in deze class wordt gebruikt, dit komt door [Authorize(AuthenticationSchemes = "Spotify")] die de pagina compleet afvangt

        /*private readonly ILogger<SpotifyLoginModel> _logger;

        public SpotifyLoginModel(ILogger<SpotifyLoginModel> logger)
        {
            _logger = logger;
        }

        public async void OnGetAsync()
        {
            await HttpContext.GetTokenAsync("Spotify", null);
        }*/
    }
}

Pages/SpotifyRequest.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SpotifyAPI.Web;
using SpotifyAPI.Web.Models;
using SpotifyAPI.Web.Enums;
using Tunix.Extensions;
using Tunix.Models;

namespace Tunix
{
    public class SpotifyRequestModel : PageModel
    {
        public FullTrack Track { get; set; }
        public PrivateProfile Profile { get; set; }
        public SearchItem SearchResult { get; set; }
        public string AccessToken { get; set; }
        [BindProperty]
        public string SearchRequest { get; set; }
        
        public void OnGet()
        {
            AuthInfo authInfo = HttpContext.Session.GetObject<AuthInfo>("AuthInfo");
            AccessToken = authInfo.AccessToken;
        }

        public async Task<IActionResult> OnPostAccount()
        {
            SpotifyWebAPI api = HttpContext.Session.GetObject<SpotifyWebAPI>("api");

            AvailabeDevices Device = await api.GetDevicesAsync();
            if (Device.Devices != null)
            {
                
            }

            PlaybackContext Playback = await api.GetPlayingTrackAsync();
            Track = Playback.Item;

            Profile = await api.GetPrivateProfileAsync();
            if (!Profile.HasError())
            {
                
            }

            return Page();
        }

        public async void OnPostPause()
        {
            SpotifyWebAPI api = HttpContext.Session.GetObject<SpotifyWebAPI>("api");

            AvailabeDevices Device = await api.GetDevicesAsync();
            if (Device.Devices != null)
            {
                //HttpContext.Session.SetString("DevID", device.Devices[0].Id.ToString());
                ErrorResponse error = await api.PausePlaybackAsync(Device.Devices[0].Id.ToString());
            }
        }

        public IActionResult OnPostTriggerPlayback()
        {
            AuthInfo authInfo = HttpContext.Session.GetObject<AuthInfo>("AuthInfo");
            AccessToken = authInfo.AccessToken;
            return Page();
        }

        public void OnPostPlay()
        {
            SpotifyWebAPI api = HttpContext.Session.GetObject<SpotifyWebAPI>("api");
            PlaybackContext test = api.GetPlayingTrack();
            string contextUri = test.Context.Uri;

            AvailabeDevices Device = api.GetDevices();
            if (Device.Devices != null)
            {
               //api.ResumePlayback(Device.Devices[0].ToString(),contextUri);
            }
        }

        public async Task<IActionResult> OnPostSearch()
        {
            SpotifyWebAPI api = HttpContext.Session.GetObject<SpotifyWebAPI>("api");
            
            SearchResult = await api.SearchItemsAsync(SearchRequest, SearchType.Track);
            return Page();
        }

        public JsonResult OnPostSearch2()
        {
            SpotifyWebAPI api = HttpContext.Session.GetObject<SpotifyWebAPI>("api");

            SearchResult = api.SearchItems(SearchRequest, SearchType.Track);

            return new JsonResult(SearchResult);
        }
    }
}

Pages/Tv_mode.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SpotifyAPI.Web;
using SpotifyAPI.Web.Enums;
using SpotifyAPI.Web.Models;
using Tunix.Classes;
using Tunix.Extensions;
using Tunix.Models;

namespace Tunix.Pages
{
    public class Tv_modeModel : PageModel
    {
        public string AccessToken { get; set; }
        Queue<FullTrack> queue = new Queue<FullTrack>();
        private int progress;

        public void OnGet()
        {
            AuthInfo authInfo = HttpContext.Session.GetObject<AuthInfo>("AuthInfo");
            AccessToken = authInfo.AccessToken;
        }

        public JsonResult OnGetQueue()
        {
            List<FullTrack> TrackList = new List<FullTrack>();
            Queue<FullTrack> TrackQueue = HttpContext.Session.GetObject<Queue<FullTrack>>("queue");

            if (TrackQueue != null)
            {
                int Counter = TrackQueue.Count();

                for (int i = 0; i < Counter; i++) { 
                    TrackList.Add(TrackQueue.Peek());
                    TrackQueue.Dequeue();
                }
            }
            return new JsonResult(TrackList);
        }

        public void OnGetPlayQueue(string Id)
        {
            string DeviceID = "";
            SpotifyWebAPI api = HttpContext.Session.GetObject<SpotifyWebAPI>("api");
            string trackuri = "spotify:track:" + Id;
            AvailabeDevices Device = api.GetDevices();

            foreach (var devices in Device.Devices)
            {
                if (devices.Name == "Tunix")
                {
                    DeviceID = devices.Id;
                    break;
                }
            }

            if (Device.Devices != null)
            {
                List<string> trackuris = new List<string> { trackuri };
                ErrorResponse error = api.ResumePlayback(DeviceID, null, trackuris, 0, 0);

            }
        }

        public void OnGetPause()
        {
            string DeviceID = "";
            SpotifyWebAPI api = HttpContext.Session.GetObject<SpotifyWebAPI>("api");
            AvailabeDevices Device = api.GetDevices();

            foreach (var devices in Device.Devices)
            {
                if (devices.Name == "Tunix")
                {
                    DeviceID = devices.Id;
                    break;
                }
            }
            PlaybackContext playback = api.GetPlayback();
            
            HttpContext.Session.SetInt32("progress", playback.ProgressMs);

            if (Device.Devices != null)
            {
                api.PausePlayback(DeviceID);
            }
        }

        public void OnGetPlay(string Id)
        {
            string DeviceID = "";
            SpotifyWebAPI api = HttpContext.Session.GetObject<SpotifyWebAPI>("api");
            string trackuri = "spotify:track:" + Id;
            AvailabeDevices Device = api.GetDevices();
   

            foreach (var devices in Device.Devices)
            {
                if (devices.Name == "Tunix")
                {
                    DeviceID = devices.Id;
                    break;
                }
            }

            if (Device.Devices != null)
            {
                List<string> trackuris = new List<string> { trackuri };
                string progress2 = HttpContext.Session.GetInt32("progress").ToString();
                api.ResumePlayback(DeviceID, null, trackuris, 0, int.Parse(progress2));
                 
            }
        }
    }
}

Pages/test.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Tunix.Models;
using Microsoft.AspNetCore.Http;
using Tunix.Classes;
using SpotifyAPI.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Tunix.Extensions;
using SpotifyAPI.Web.Models;

namespace Tunix.Pages
{
    
    public class TestModel : PageModel
    {
        private readonly ILogger<TestModel> _logger;
        public string Result { get; set; }
        public string Query { get; }
        public List<Account> outputList { get; set; }

        public SpotifyWebAPI api { get; set; }

        public string AccessToken { get; set; }
        public string code { get; set; } = "Not set yet";

        private Authenticate auth = new Authenticate();

        [BindProperty]
        public string Username { get; set; }
        [BindProperty]
        public string Password { get; set; }

        public TestModel(ILogger<TestModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            outputList = auth.GetAccount();
            //code = HttpContext.Session.GetString("AccessToken");
        }

        public IActionResult OnPostRequest()
        {
            return RedirectToPage("SpotifyRequest");
        }

        public IActionResult OnPostGenerate()
        {
            outputList = auth.GetAccount();

            AuthInfo authInfo = HttpContext.Session.GetObject<AuthInfo>("AuthInfo");
            code = authInfo.AccessToken;
            return Page();
        }

        public IActionResult OnPostLogin()
        {
            if (Username!= null && Password != null)
            {
                HttpContext.Session.SetString("username", Username);
                HttpContext.Session.SetString("password", Password);
                Result += "Login valid";
                return Page();
            }
            else
            {
                Result += "Login invalid ";
                return Page();
            }
        }

        public IActionResult OnPostRegister()
        {
            if (Username != null && Password != null)
            {
                HttpContext.Session.SetString("username", Username);
                HttpContext.Session.SetString("password", Password);

                if (Username != null && Password != null)
                {
                    if (auth.SetAccount(Username, Password))
                    {
                        Result = "Register successful";
                    }
                    else
                    {
                        Result = "Register unsuccessful";
                    }
                }
                else
                {
                    Result = "Username and/or password empty";
                }
                return Page();
            }
            else
            {
                Result += "Login invalid ";
                return Page();
            }
        }
    }
}

Pages/Dashboard.cshtml
@page
@model Tunix.DashboardModel
@{
    ViewData["Title"] = "Dashboard";
    Layout = "~/Pages/Shared/_LayoutDashboard.cshtml";
}

<script src="https://sdk.scdn.co/spotify-player.js"></script>
<script>
    window.onSpotifyWebPlaybackSDKReady = () => {
      const token = '@Model.AccessToken';
      const player = new Spotify.Player({
        name: 'Tunix',
        getOAuthToken: cb => { cb(token); }
      });

      // Error handling
      player.addListener('initialization_error', ({ message }) => { console.error(message); });
      player.addListener('authentication_error', ({ message }) => { console.error(message); });
      player.addListener('account_error', ({ message }) => { console.error(message); });
      player.addListener('playback_error', ({ message }) => { console.error(message); });

      // Playback status updates
      player.addListener('player_state_changed', state => { console.log(state); });

      // Ready
      player.addListener('ready', ({ device_id }) => {
        console.log('Ready with Device ID', device_id);
      });

      // Not Ready
      player.addListener('not_ready', ({ device_id }) => {
        console.log('Device ID has gone offline', device_id);
      });

      // Connect to the player!
        player.connect();
    };
</script>
<main id="content">
    <div class="section">
        <div class="row searchBlock">
            <div class="row titleBlock">
                <div class="col-12 titleContainer">
                    <span>Discover</span>
                </div>
            </div>
            <div class="row inputBlock">
                <div class="col-12 inputContainer">
                    <input id="search" type="text" placeholder="Search">
                </div>
                <div class="col-12 searchContainer">
                    <div class="row searchResult">

                    </div>
                </div>
            </div>
            <div class="row scrollContainer">
                <div class="col-12 scrollanimation">
                    <div class="ScrollIcon">
                        <div class="Finger"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="section">
        <div class="row playlistBlock">

            <div class="row titleBlock">
                <div class="col-12 titleContainer">
                    <span>Playlist</span>
                </div>
            </div>

            <div class="col-12 coverOuter">
                <div class="coverInner">
                    <img src="" alt="">
                </div>
            </div>

            <div class="row queueBlock">
                <div class="col-9 queueContainer">
                    <ul class="playlist">
                        <li class="col-12" rel="1"><a>No Songs Found</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="section">
        <div class="row inspirationBlock">

            <div class="row titleBlock">
                <div class="col-12 titleContainer">
                    <span>Inspiration</span>
                </div>
            </div>

            <div class="row carouselBlock">

                <div class="col-12 slideOuter prevHide">
                    <div class="slideInner">
                        <img src="img/beerbongs.jpg">
                        <div class="slideInfo">
                            <span>Beerbongs and Bentleys</span>
                        </div>
                    </div>
                </div>

                <div class="col-12 slideOuter prevSecond">
                    <div class="slideInner">
                        <img src="img/scorpion.jpg">
                        <div class="slideInfo">
                            <span>Scorpion</span>
                        </div>
                    </div>
                </div>

                <div class="col-12 slideOuter prev">
                    <div class="slideInner">
                        <img src="img/thankyou.jpg">
                        <div class="slideInfo">
                            <span>Thank You, Next</span>
                        </div>
                    </div>
                </div>

                <div class="col-12 slideOuter selected">
                    <div class="slideInner">
                        <img src="img/senorita.jpg">
                        <div class="slideInfo">
                            <span>Señorita</span>
                        </div>
                    </div>
                </div>

                <div class="col-12 slideOuter next">
                    <div class="slideInner">
                        <img src="img/astroworld.jpg">
                        <div class="slideInfo">
                            <span>Astroworld</span>
                        </div>
                    </div>
                </div>

                <div class="col-12 slideOuter nextSecond">
                    <div class="slideInner">
                        <img src="img/starboy.jpg">
                        <div class="slideInfo">
                            <span>Starboy</span>
                        </div>
                    </div>
                </div>

                <div class="col-12 slideOuter nextHide">
                    <div class="slideInner">
                        <img src="img/divide.jpg">
                        <div class="slideInfo">
                            <span>Divide</span>
                        </div>
                    </div>
                </div>

            </div>

            <div class="row consoleBlock">
                <div class="col-12 consoleContainer"><i class="fas fa-chevron-left"></i><i class="fas fa-chevron-right"></i></div>
            </div>

        </div>
    </div>

</main>

Pages/SpotifyLogin.cshtml
@page
@model SpotifyLoginModel
@{
    ViewData["Title"] = "Auth";
}
<h1>@ViewData["Title"]</h1>

Pages/SpotifyRequest.cshtml
@page
@model Tunix.SpotifyRequestModel
@{
    ViewData["Title"] = "SpotifyRequest";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}
<script src="https://sdk.scdn.co/spotify-player.js"></script>
<script>
    window.onSpotifyWebPlaybackSDKReady = () => {
      const token = '@Model.AccessToken';
      console.log('@Model.AccessToken');
      const player = new Spotify.Player({
        name: 'Tunix',
        getOAuthToken: cb => { cb(token); }
      });

      // Error handling
      player.addListener('initialization_error', ({ message }) => { console.error(message); });
      player.addListener('authentication_error', ({ message }) => { console.error(message); });
      player.addListener('account_error', ({ message }) => { console.error(message); });
      player.addListener('playback_error', ({ message }) => { console.error(message); });

      // Playback status updates
      player.addListener('player_state_changed', state => { console.log(state); });

      // Ready
      player.addListener('ready', ({ device_id }) => {
        console.log('Ready with Device ID', device_id);
      });

      // Not Ready
      player.addListener('not_ready', ({ device_id }) => {
        console.log('Device ID has gone offline', device_id);
      });

      // Connect to the player!
        player.connect();
    };
</script>
<div class="text-center" style="background-color:white;padding-bottom:50px">
    <h1>SpotifyRequest</h1>

    <form method="post">
        <input type="submit" asp-page-handler="Account" value="Get Info" />
    </form>
    <h1><b>Profile info</b></h1>
    @{ if (Model.Profile != null)
        {
            if (Model.Profile.DisplayName != null)
            {
                <p><b>Displayname:</b> @Model.Profile.DisplayName.ToString()</p>

                <br />
            }
            if (Model.Profile.Birthdate != null)
            {
                <p><b>Birthdate:</b> @Model.Profile.Birthdate.ToString()</p>
                <br />
            }
            if (Model.Profile.Country != null)
            {
                <p><b>Country:</b> @Model.Profile.Country.ToString()</p>
                <br />
            }
            if (Model.Profile.Email != null)
            {
                <p><b>Email:</b> @Model.Profile.Email.ToString()</p>
                <br />
            }
            if (Model.Profile.Images.Count != 0)
            {

                <p><b>Photo:</b><img src="@Model.Profile.Images[0].Url.ToString()" /></p>
                <br />
            }
            <hr>
        }
    }

    <h1><b>Track info</b></h1>

    @{
        if (Model.Track != null)
        {
            if (Model.Track.Album != null)
            {
                <p><b>Current Album:</b> @Model.Track.Album.Name.ToString()</p>
                <p>
                    <img src="@Model.Track.Album.Images[1].Url" />
                </p>
                <br />

            }

            if (Model.Track.Name != null)
            {
                <p><b>Current Track name:</b> @Model.Track.Name.ToString()</p>
                <br />
            }
            if (Model.Track.Artists != null)
            {
                <p><b>Current Artists:</b></p>
                foreach (var artist in Model.Track.Artists)
                {
                    <p><b>Name:</b> @artist.Name.ToString()</p>
                    <p><b>Type:</b> @artist.Type.ToString()</p>
                    <br />
                }
                <br />
            }
            if (Model.Track.Artists != null)
            {
                <p><b>Current Track type:</b> @Model.Track.Type.ToString()</p>
                <br />
            }
        }
    }
    <form method="post">
        <input type="submit" asp-page-handler="TriggerPlayback" value="Trigger" />
    </form>

    <form method="post">
        <input type="submit" asp-page-handler="Pause" value="Pause" />
    </form>

    <form method="post">
        <input type="submit" asp-page-handler="Play" value="Play" />
    </form>



    <form method="post">
        <table>
            <tr><th colspan="2">Search Function</th></tr>
            <tr>
                <td>Search Track</td>
                <td><input type="text" asp-for="@Model.SearchRequest" /></td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td><input type="submit" value="Search" asp-page-handler="Search" /></td>
            </tr>
        </table>
    </form>
    <h1><b>Search Result</b></h1>

    @{
        if (Model.SearchResult != null)
        {
            foreach (var item in Model.SearchResult.Tracks.Items)
            {
                <p><b>item Name:</b>@item.Name.ToString()</p>
                <p><b>item Artists:</b></p>
                foreach (var artist in item.Artists)
                {
                    <p><b>Name:</b> @artist.Name.ToString()</p>
                }
                <img src="@item.Album.Images[2].Url" />
                <hr />
            }
        }
    }

</div>

Pages/callback.cshtml
@page
@model Tunix.Pages.CallbackModel

Pages/test.cshtml
@page
@model TestModel
@{
    ViewData["Title"] = "Home page";
}

    <div class="text-center" style="background-color:white;padding-bottom:50px">
        @{
            if (Model.Result != null)
            {
                <div class="jumbotron">
                    <h1>NOTIFICATION</h1>
                    <p>@Model.Result</p>
                </div>
            }
        }
        @Model.code
        <h1 class="display-4">Welcome</h1>
        <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>

        <form method="post" asp-page="Test">
            <table>
                <tr><th colspan="2">Login form</th></tr>
                <tr>
                    <td>Username</td>
                    <td><input type="text" asp-for="@Model.Username" /></td>
                </tr>
                <tr>
                    <td>Password</td>
                    <td><input type="password" asp-for="@Model.Password" /></td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td><input type="submit" value="Login" asp-page-handler="Login" /></td>
                </tr>
            </table>
        </form>

        <form method="post" asp-page="Test">
            <table>
                <tr><th colspan="2">Register form</th></tr>
                <tr>
                    <td>Username</td>
                    <td><input type="text" asp-for="@Model.Username" /></td>
                </tr>
                <tr>
                    <td>Password</td>
                    <td><input type="password" asp-for="@Model.Password" /></td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td><input type="submit" value="Register" asp-page-handler="Register" /></td>
                </tr>
            </table>
        </form>
        <form asp-page-handler="request" method="post">
            <button class="btn btn-danger">Request</button>
        </form>
        <button><a href="/SpotifyLogin">Get Token</a></button>
        @{ if (Model.code != null)
            {
                <h1>AccessToken: @Model.code</h1>

            }
            else
            {
                <h1>No AccessToken</h1>
            }
        }
        <table style="margin:0 auto 20px auto">
            <tr>
                <th>Id</th>
                <th>Username</th>
                <th>Password</th>
            </tr>
            @{ if (Model.outputList != null)
                {
                    foreach (Models.Account account in Model.outputList)
                    {
                        <tr>
                            <td>@account.id</td>
                            <td>@account.username</td>
                            <td>@account.password</td>
                        </tr>
                    }
                }
                else
                {
                    <tr><td colspan="3">Output is empty</td></tr>
                }
            }
        </table>
        <form method="post" asp-page="Test">
            <input type="text" asp-for="@Model.Query" />
            <input type="submit" value="Generate" asp-page-handler="Generate" />
        </form>
    </div>